Feature/scan 410 store burned items
UniqueNetwork/unique-scan-backend pull request #117
Opened 2022-09-19 06:23 UTC by AzgatG

2022-09-27 08:22 UTC, chernetsky requested changes

2022-09-27 08:22 UTC, chernetsky commented on apps/crawler/src/subscribers/collections.subscriber.service.ts
> +    hash: string,
Предлагаю везде этот параметр вместо hash переименовать его в blockHash. Потому что хеши бывают разные. А так будет понятно о чём речь.

2022-09-27 08:22 UTC, chernetsky commented on apps/crawler/src/subscribers/collections.subscriber.service.ts
> +      block: { height: blockNumber, timestamp: blockTimestamp, hash },
Вот в таких местах предлагаю тоже сделать 
`const { hash: blockHash } = ctx;` По аналогии с timestamp и height.

2022-09-27 08:22 UTC, chernetsky commented on apps/crawler/src/writers/collection.writer.service.ts
>    private async deleteCollectionWithTokens(collectionId: number) {
А нам теперь этот метод не нужен? Может удалить?

2022-09-27 08:22 UTC, chernetsky commented on apps/web-api/src/tokens/token.dto.ts
> +  was_burn?: boolean;
Есть подозрение, что _was burn_ - это неграмотно) [Правильно](https://www.wordreference.com/conj/enverbs.aspx?v=burn) либо was burnt/burned или просто burnt/burned. Выбирай на вкус)) Мне нравится и _was_burned_ и _burned_.

2022-10-04 06:00 UTC, chernetsky reviewed
Let's remove _delete()_ methods from TokenService and CollectionService, because they are replaced by _burn()_ methods and are no longer used.

2022-10-05 02:34 UTC, chernetsky submitted a review, later dismissed

2022-10-11 06:18 UTC, sswebcoder commented on apps/crawler/src/sdk/sdk.service.ts
> +      result = property?.propertyPermissions;
We can return propertyPermissions in this case.

2022-10-11 06:19 UTC, sswebcoder commented on apps/crawler/src/sdk/sdk.service.ts
> +    return result;
Or return empty array if catch error.

2022-10-11 06:27 UTC, sswebcoder commented on apps/crawler/src/services/collection.service.ts
>        this.sdkService.getTokenPropertyPermissions(collectionId),
Is it correct to return property permission in out of block state?

2022-10-11 06:55 UTC, sswebcoder commented on migrations/1664975508835-burned-tokens-triggers.ts
> +      if  (TG_OP = 'INSERT') then
Should we check what token was not burned?

2022-10-11 06:55 UTC, sswebcoder commented on migrations/1664975508835-burned-tokens-triggers.ts
> +      if  (TG_OP = 'INSERT') then
For rescan case.

2022-10-11 06:56 UTC, sswebcoder commented on migrations/1664975508835-burned-tokens-triggers.ts
> +  if (TG_OP = 'INSERT') then
Same question like tokens stats.

2022-10-17 06:58 UTC, sswebcoder submitted a review, later dismissed

2022-10-17 08:08 UTC, sswebcoder approved these changes

2022-10-17 08:09 UTC, merged