[WIP]Feature/scan 270 store blocks
UniqueNetwork/unique-scan-backend pull request #43
Opened 2022-07-12 12:37 UTC by AzgatG

2022-07-13 03:57 UTC, chernetsky requested changes
There are some other issues that we'll discuss in Slack.

2022-07-13 03:57 UTC, chernetsky commented on apps/crawler/src/processors/block-processor.ts
> +      if (blockData) {
What if no blockData? Now we just log that everything is ok. Maybe here we should log that something wrong? Or maybe remove this `if(blockData) {}`

2022-07-13 03:57 UTC, chernetsky commented on apps/crawler/src/processors/events-processor.ts
> +      if (data) {
What if no `data`? What cases for this? Log error?

2022-07-13 03:57 UTC, chernetsky commented on apps/crawler/src/processors/events-processor.ts
> +      phase: event.extrinsic
I think should not create values for fields "just because before they were like this") Don't we have raw event phase value it response?

2022-07-13 03:57 UTC, chernetsky commented on apps/crawler/src/processors/extrinsic-processor.ts
> +    const sdkApi = await this.sdkService.getSdk();
We are not supposed to get sdk api object from here. SdkService class created just for this. You should add new method something like `SdkService.getBlockEvents(hash)`.

2022-07-13 03:57 UTC, chernetsky commented on apps/crawler/src/processors/extrinsic-processor.ts
> +      is_signed: true,
I'm not shure it's correct. Some extrinsics are not signed. For example timestamp.set. Why don't check extrinsic.isSigned field?

2022-07-13 03:57 UTC, chernetsky commented on apps/crawler/src/processors/extrinsic-processor.ts
> +  'vestedTransfer',
We should avoid usage of string literals. Use constant enums from constants.ts.

2022-07-13 03:57 UTC, chernetsky commented on common/utils/utils.service.ts
> +import { encodeAddress, decodeAddress } from '@polkadot/util-crypto';
I think all of the methods of this class should be static and used like Utils.mothodName istead of this.utils.methodName.

2022-07-13 04:09 UTC, chernetsky commented on apps/crawler/src/processors/extrinsic-processor.ts
> +      signer: extrinsic.signer,
There may be no signer.

2022-07-13 04:11 UTC, chernetsky commented on apps/crawler/src/sdk.service.ts
> +  async getSdk() {
This method should stay private. Just add getBlockEvents() method.

2022-08-01 05:42 UTC, AzgatG commented
switched to firesquid

2022-08-01 05:42 UTC, closed without merging

2022-08-01 05:43 UTC, AzgatG commented
switched to firesquid